before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
language: php
php:
  - "5.4"
env:
  global:
   - DB=pgsql MOODLE_VERSION=MOODLE_25_STABLE
   - secure: jOrUxTe76d5a+986dinHlXdixRn5iu+KdE7P9FSokV1dppflD7JBql1kWO4Zb2hYkPe9Zqc0UR/6Yb8mZd8a+Aj9FnGWZM0mZxAQzASL+8f7PV19JyGsi5wG/MqY0ZoVSnkQ2jmCOz8nG78BIM/wJIcqWL+COELIUQwZ8S78EwypY2M15CsuVGkToUI7lboo7ricmECACn+u7vTUJjrrvZoFyRsHc5K+d+vgW8KPgEw0dt/rtuUv/CCndUwYJXZDqPmCwLrz9CtWl+6MvGhYlWb9WWwmXKKN/sOs21YszDb1C7NFH+V5VcexnkooohIRN+CmTO+pYdpj6X33L1eHng==
before_script:
 - git clone git://github.com/moodle/moodle ../moodle && cd ../moodle
 - git checkout $MOODLE_VERSION
 - sudo apt-get update > /dev/null
 - mv ../moodle-auth_googleoauth2 auth/googleoauth2
 - curl -s https://getcomposer.org/installer | php
 - echo "{\"config\":{\"github-oauth\":{\"github.com\":\"$GITHUBTOKEN\"}}}" > ~/.composer/config.json
 - php composer.phar install --dev
 - cp config-dist.php config.php
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*phpu\)%\n\1%' config.php"
 - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*bht\)%\n\1%' config.php"
 - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; fi"
 - sh -c "if [ '$DB' = 'mysqli' ]; then sed -i -e s/\'pgsql\'/\'mysqli\'/ -e s/\'username\'/\'root\'/ config.php; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database moodle;' -U postgres; fi"
 - sh -c "if [ '$DB' = 'pgsql' ]; then sed -i s/\'username\'/\'postgres\'/ config.php; fi"
 - mkdir -m777 $HOME/moodledata
 - php admin/tool/phpunit/cli/init.php
 - "(php -S localhost:8000 &) 2> /dev/null > /dev/null"
 - "wget http://selenium-release.storage.googleapis.com/2.43/selenium-server-standalone-2.43.1.jar"
 - "java -jar selenium-server-standalone-2.43.1.jar &"
 - php admin/tool/behat/cli/init.php
script:
 - vendor/bin/behat --config /home/shippable/bht_moodledata/behat/behat.yml --tags @auth_googleoauth2;
 - vendor/bin/phpunit auth_googleoauth2_lib_testcase auth/googleoauth2/tests/lib_test.php
